Feature setting up the project
marcinel123/ip-address-tracker pull request #4
Opened 2023-03-10 19:55 UTC by marcinel123

Hi Adam,

I created and pushed here some basic structure of the project. 

- created first 3 components
- installed leaflet dependencies and added basic map so I can see it works
- added background to theme of tailwind config also so I can see it works well

Before I go any further please have a look at all changes and let me know if it is acceptable.

Regards,
Martin

2023-03-14 22:38 UTC, AdamKniec requested changes
Some small comments. The most important thing is linter.

2023-03-14 22:38 UTC, AdamKniec commented on package.json
> +    "@types/leaflet": "^1.9.1",
👍

2023-03-14 22:38 UTC, AdamKniec commented on src/App.tsx
> +		<>
Something is wrong again with formatting :(

2023-03-14 22:38 UTC, AdamKniec commented on src/Components/DisplayDataComponent.tsx
> +export const DisplayDataComponent = () => {
Please change the name.  I guess You are trying to create a component that will be responsible for displaying the location details. Name should be more specific. DisplayDataComponent might mean everything and nothing at the same time ;)

2023-03-14 22:38 UTC, AdamKniec commented on src/Components/MapComponent.tsx
> +export const MapComponent = () => {
Change the name to Map. It's a functional component because it starts with a big letter so there is no need to include "component" in name

2023-03-14 22:38 UTC, AdamKniec commented on src/Components/SearchComponent.tsx
> +export const SearchComponent = () => {
Remove "component" from name

2023-03-14 22:38 UTC, AdamKniec commented on src/Components/MapComponent.tsx
> +import "leaflet/dist/leaflet.css";
Is this import necessary?

2023-03-15 16:43 UTC, marcinel123 commented on src/App.tsx
> +		<>
are you sure, you have got a newest version? because there should not be Hello component any more in this pull request.

2023-03-15 16:54 UTC, marcinel123 commented on src/Components/DisplayDataComponent.tsx
> +export const DisplayDataComponent = () => {
name has been changed.

2023-03-15 16:54 UTC, marcinel123 commented on src/Components/MapComponent.tsx
> +export const MapComponent = () => {
changed.

2023-03-15 16:54 UTC, marcinel123 commented on src/Components/SearchComponent.tsx
> +export const SearchComponent = () => {
changed.

2023-03-15 16:56 UTC, marcinel123 commented on src/Components/MapComponent.tsx
> +import "leaflet/dist/leaflet.css";
without this import map is not showing correctly in the app. I checked some information about leaflet in Internet and usually everyone uses this import.

2023-03-15 19:30 UTC, AdamKniec approved these changes

2023-03-16 05:18 UTC, merged