added basic styles to location-details-component
marcinel123/ip-address-tracker pull request #6
Opened 2023-03-16 07:07 UTC by marcinel123

Hi Adam,

I added only basic styles to location detail component but I have a problem with setting the height of this component.

I set the height to 1/5 of the screen and I want to translate it -50%. It sets height correctly and moves the whole div -50% to the top. But there still remains white space between Search and Map.

I attached the screen of this problem.

<img width="936" alt="location_component" src="https://user-images.githubusercontent.com/95523781/225540331-cb4e22dc-7b36-4091-b1d6-e0481bfc114e.png">

Please have a look at this issue.

Thanks,
Martin

2023-03-17 20:10 UTC, AdamKniec commented on src/Components/LocationDetails.tsx
> +				<h3>Ip Address</h3>
Is this really a header?

2023-03-17 20:12 UTC, AdamKniec requested changes
We do not merge this PR until the component height issue is resolved.

2023-03-19 19:02 UTC, marcinel123 commented
Please have a look as I finished location component styling.

regards,
Martin

2023-03-20 17:40 UTC, marcinel123 commented
Please have a look after all changes.

regards,
Martin

2023-03-20 20:14 UTC, marcinel123 commented on src/Components/LocationDetails.tsx
> +				<h3>Ip Address</h3>
fixed

2023-03-20 20:15 UTC, AdamKniec approved these changes

2023-03-20 20:16 UTC, merged